print("Enter a number for times table ")
sNumber = input()
iNumber = int(sNumber)
print("1 x " + str(iNumber) + " = " + str(iNumber))
print("2 x " + str(iNumber) + " = " + str(iNumber * 2))
print("3 x " + str(iNumber) + " = " + str(iNumber * 3))
print("4 x " + str(iNumber) + " = " + str(iNumber * 4))
print("5 x " + str(iNumber) + " = " + str(iNumber * 5))
print("6 x " + str(iNumber) + " = " + str(iNumber * 6))
print("7 x " + str(iNumber) + " = " + str(iNumber * 7))
print("8 x " + str(iNumber) + " = " + str(iNumber * 8))
print("9 x " + str(iNumber) + " = " + str(iNumber * 9))
print("10 x " + str(iNumber) + " = " + str(iNumber * 10))
print("11 x " + str(iNumber) + " = " + str(iNumber * 11))
print("12 x " + str(iNumber) + " = " + str(iNumber * 12))
